#include <assert.h>
#include <atomic>
#include <chrono>
#include <format>
#include <iostream>
#include <mutex>
#include <optional>
#include <shared_mutex>
#include <thread>
#include <utility>
#include <windows.h>